name: ppg-entropy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyter
  - jupyterlab
  - ipykernel
  - pip
  - pip:
    - antropy          # approximate/sample/permutation entropy
